/* INSERTS FOR 3 TABLES, OTHERWISE KNOWN AS 
THE REQUIRED DATA TO BE RECORDED */

-- BILLS DATA
INSERT INTO BILLS
VALUES ('PHONE COMPANY', 125, 1);
INSERT INTO BILLS 
VALUES('POWER COMPANY', 75, 1);
INSERT INTO BILLS 
VALUES('RECORD CLUB', 25, 2);
INSERT INTO BILLS
VALUES('SOFTWARE COMPANY', 35, 3);
INSERT INTO BILLS
VALUES ('CABLE TV COMPANY', 35, 1);

-- BANK_ACCOUNTS DATA
INSERT INTO BANK_ACCOUNTS
VALUES (1, 'CHECKING', 500, 'FIRST FEDERAL');
INSERT INTO BANK_ACCOUNTS
VALUES (2, 'MONEY MARKET', 1200, "FIRST INVESTOR'S");
INSERT INTO BANK_ACCOUNTS
VALUES (3, 'CHECKING', 90, 'CREDIT UNION');

-- COMPANY DATA
INSERT INTO COMPANY
VALUES ('PHONE COMPANY', '111 1ST STREET', 'ATLANTA', 'GA');
INSERT INTO COMPANY
VALUES ('POWER COMPANY', '222 2ND STREET', 'JACKSONVILLE', 'FL');
INSERT INTO COMPANY
VALUES ('RECORD CLUB', '333 3RD AVENUE', 'LOS ANGELES', 'CA');
INSERT INTO COMPANY
VALUES ('SOFTWARE COMPANY', '444 4TH DRIVE', 'SAN FRANCISCO', 'CA');
INSERT INTO COMPANY
VALUES ('CABLE TV COMPANY', '555 5TH DRIVE', 'AUSTIN', 'TX');


